update gpuagent to latest submodule pull and build infra within exporter (#846)

diff --git a/Makefile.compile b/Makefile.compile
--- a/Makefile.compile
+++ b/Makefile.compile
@@ -56,31 +56,53 @@ amdsmi-compile-azure:
 # compiles the gpuagent from source
 # gpuagent is a static go binary which is agnostic of platform, so we can
 # build it once with any of the prebuilt libamdsmi library file we support
-# RHEL9 being default. workspace built binary is being used if exists else revert to
-# prebuilt one from repo
+# RHEL9 being default. updates the assets for all the components.
 .PHONY: gpuagent-compile
 gpuagent-compile:
+	@echo "prereq build container using make gpuagent-build"
+	@cd gpuagent && git submodule update --init  --recursive && cd -
+	@cd gpuagent && git checkout ${GPUAGENT_COMMIT} && cd -
 	@docker run --rm -it --privileged \
+		--name gpuagent-builder \
+		--network host \
 		-e "USER_NAME=$(shell whoami)" \
 		-e "USER_UID=$(shell id -u)" \
 		-e "USER_GID=$(shell id -g)" \
-		--name gpuagentbuild -v $(GPUAGENT_SRC_DIR):$(GPUAGENT_CONTAINER_WORKDIR) \
-		-w $(GPUAGENT_CONTAINER_WORKDIR) $(GPUAGENT_BUILDER_IMAGE)
-	@cd $(TOP_DIR)/gpuagent && git checkout sw/nic/third-party/rocm/amd_smi_lib
+		-e "GIT_COMMIT=${GIT_COMMIT}" \
+		-e "GIT_VERSION=${GIT_VERSION}" \
+		-e "BUILD_DATE=${BUILD_DATE}" \
+		-v $(GPUAGENT_SRC_DIR):$(GPUAGENT_CONTAINER_WORKDIR) \
+		-w $(GPUAGENT_CONTAINER_WORKDIR) \
+		${GPUAGENT_BUILDER_IMAGE} \
+		/bin/bash -c "cd $(GPUAGENT_CONTAINER_WORKDIR) && source ~/.bashrc && make gopkglist && make -C sw/nic/gpuagent -j$(shell nproc) all"
+	${MAKE} gpuagent-asset-copy
 
-.PHONY: gpuagent-compile-full
-gpuagent-compile-full: 
-	TOP_DIR=$(TOP_DIR) OS=RHEL9 $(ASSET_COPY_SCRIPT) || true
-	${MAKE} gpuagent-compile
-	@if [ $$? -ne 0 ]; then \
-		echo "gpuagent-compile failed"; \
-		exit 1; \
-	else \
-		echo "Copying gpuagent to assets"; \
-		mkdir -p ${TOP_DIR}/build/assets/ || true; \\
-		cp -vf $(GPUAGENT_OUT_DIR)/gpuagent $(TOP_DIR)/build/assets/gpuagent; \
-		echo "file copied successfully to $(TOP_DIR)/build/assets/gpuagent"; \
-	fi
+.PHONY: gpuagent-asset-copy
+gpuagent-asset-copy:
+	@echo "prereq gpuagent-compile is finished with all binaries created"
+	@for file in gpuagent gpuagent_gim gpuagent_mock gpuctl; do \
+		if [ -f "$(GPUAGENT_SRC_DIR)/sw/nic/build/x86_64/sim/bin/$$file" ]; then \
+			echo "Found: $$file"; \
+		else \
+			echo "Missing: $$file"; \
+			exit 1; \
+		fi \
+	done
+	@for file in gpuagent gpuagent_gim gpuagent_mock; do \
+		cp -vf $(GPUAGENT_SRC_DIR)/sw/nic/build/x86_64/sim/bin/$$file ${ASSETS_PATH}/gpuagent && \
+		strip ${ASSETS_PATH}/gpuagent && \
+		echo "source file $$file" && \
+		tar_file=$$(echo $$file | sed 's/gpuagent_gim/gpuagent_sriov_static/' | sed 's/gpuagent$$/gpuagent_static/').bin.gz && \
+		cd ${ASSETS_PATH} && tar czf $$tar_file gpuagent && chmod +x $$tar_file gpuagent && \
+		echo "Created tar file: ${ASSETS_PATH}/$$tar_file"; \
+	done
+	@rm -f ${ASSETS_PATH}/gpuagent || true
+	@cp -vf $(GPUAGENT_SRC_DIR)/sw/nic/build/x86_64/sim/bin/gpuctl ${ASSETS_PATH}/gpuctl.gobin
+	@strip ${ASSETS_PATH}/gpuctl.gobin
+	@echo "gpuagent assets copied successfully"
+	@cd ${TOP_DIR}
+
+	
 
 .PHONY: rocprofiler-compile
 rocprofiler-compile:
